name = input("Enter your full name: ")
# phone_number = input("Enter your phone number #: ")

# result = len(name)
# result = name.find(" ")
# result = name.rfind("n")
# name = name.capitalize()
# name = name.upper()
# name = name.lower()
# result = name.isdigit()
result = name.isalpha()
# result = phone_number.count("1")
# result = phone_number.replace("-", "")
print(result)
